### ISSUE TITLE
[QUESTION] Is Snake vulnerable to issue 3489?

### ISSUE THREAD

**Issue by kozross** [Snake-Edition/P32-FW#56]
[Issue in question](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3489). The fix is [straightforward](https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/3613), but Prusa are dragging their feet about it. Is this an issue with Snake-FW, and if so, can it be fixed using this patch?

**Comment by espr14** [comment]
Not yet but I'll raise the temps in the next release(s).

**Comment by kozross** [comment]
@espr14 - thanks!

**Comment by espr14** [comment]
Available since [5.1.0.2](https://github.com/Snake-Edition/P32-FW/releases/tag/v5.1.0.2)
