### ISSUE TITLE
[FEATURE REQUEST] Re-enable M303

### ISSUE THREAD

**Issue by kozross** [Snake-Edition/P32-FW#57]
Prusa [decided to remove M303 completely](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3351#issuecomment-1866926815) in their latest release. Can this be restored?

**Comment by espr14** [comment]
Can but will be harder so it won't be soon.

**Comment by jwidess** [comment]
I created a PR update the readme to strike out mentions of M303 PID Autotune FYI. https://github.com/Snake-Edition/P32-FW/pull/68
