### ISSUE TITLE
[ENHANCEMENT] <A setting to enable the Prusa logo>

### ISSUE THREAD

**Issue by xtomasnemec** [Snake-Edition/P32-FW#61]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI]

**Is your suggested improvement related to an existing problem? Please describe.**
  A clear and concise description of what the problem is. I would like to have the Prusa logo in the firmware. The menu just looks wierd without it

**Describe the expected functionality**
  A setting in the Snake settings to enable/disable the prusa branding

**Comment by espr14** [comment]
1. I want the different look to know which FW you have.
2. "Original Prusa" is registered.
3. I'd prefer different button layout or very new logo.
